DROP TABLE IF EXISTS table1;
DROP TABLE IF EXISTS table2;

CREATE TABLE table1 (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    name VARCHAR2(6),
    table2_id NUMBER NOT NULL,
    CONSTRAINT table1_id_pk PRIMARY KEY (id)
);

CREATE TABLE table2 (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    name VARCHAR2(30),
    table1_id NUMBER NOT NULL,
    CONSTRAINT table2_id_pk PRIMARY KEY (id)
);

insert into table1 values(1, 'aboba1', 1);
insert into table1 values(2, 'aboba2', 1);
insert into table1 values(3, 'aboba3', 1);
insert into table1 values(4, 'aboba4', 1);
insert into table1 values(5, 'aboba5', 1); 


insert into table2 values(1, 'dog1', 1);
insert into table2 values(2, 'dog2', 1);
insert into table2 values(3, 'dog3', 1);
insert into table2 values(4, 'dog4', 1);
insert into table2 values(5, 'dog5', 1);