INSERT INTO READER(NAME) VALUES ('JOHN');
INSERT INTO STUDENT(NAME, BIRTHDATE) VALUES ('ROAN', TO_DATE('2005/11/22', 'yyyy/mm/dd'));
INSERT INTO STUDENT(NAME, BIRTHDATE) VALUES ('ROXY', TO_DATE('2003/10/15', 'yyyy/mm/dd'));
INSERT INTO COURSE(TITLE, READER_ID) VALUES ('SQL', (SELECT ID FROM READER WHERE NAME = 'JOHN'));
INSERT INTO COURSE(TITLE, READER_ID) VALUES ('JS', (SELECT ID FROM READER WHERE NAME = 'JOHN'));

UPDATE COURSE SET TITLE = 'JavaScript' WHERE TITLE='JS';
UPDATE STUDENT SET BIRTHDATE = TO_DATE('2008/12/12', 'yyyy/mm/dd') WHERE NAME = 'ROAN';

DELETE FROM READER WHERE NAME = 'JOHN';

INSERT INTO READER(NAME) VALUES ('BOSH');

CALL REPORTS.GET_REPORT();
CALL REPORTS.GET_REPORT(TO_TIMESTAMP('2024/05/08 11:00:00', 'yyyy/mm/dd HH24:MI:SS'));

CALL BACKUP.RESTORE(TO_TIMESTAMP('2024/05/08 11:42:26', 'yyyy/mm/dd HH24:MI:SS'));
CALL BACKUP.RESTORE(INTERVAL '0' SECOND);




